// <auto-generated />

namespace PdfConversionAndTimeStampTool
{
    using Application = System.Windows.Forms.Application;
    internal static class PdfConversionAndTimeStampTool
    {
        [System.STAThread]
        private static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new PdfConversionAndTimeStampToolView());
        }
    }
}