// <auto-generated />
namespace PdfConversionAndTimeStampTool
{
    partial class PdfConversionAndTimeStampToolView
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PdfConversionAndTimeStampToolView));
            this.selectFilesButton = new System.Windows.Forms.Button();
            this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.fileView = new System.Windows.Forms.CheckedListBox();
            this.progressBar = new System.Windows.Forms.ProgressBar();
            this.openCustomScriptDialog = new System.Windows.Forms.OpenFileDialog();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.addCustomFieldButton = new System.Windows.Forms.Button();
            this.addCustomScriptButton = new System.Windows.Forms.Button();
            this.selectTiming = new System.Windows.Forms.ComboBox();
            this.scriptSelector = new System.Windows.Forms.ComboBox();
            this.convertOnlyButton = new System.Windows.Forms.Button();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.convertAndTimeStampDefaultDayButton = new System.Windows.Forms.Button();
            this.convertAndTimeStampDefaultMonthButton = new System.Windows.Forms.Button();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage2.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.SuspendLayout();
            // 
            // selectFilesButton
            // 
            this.selectFilesButton.Location = new System.Drawing.Point(8, 0);
            this.selectFilesButton.Name = "selectFilesButton";
            this.selectFilesButton.Size = new System.Drawing.Size(128, 64);
            this.selectFilesButton.TabIndex = 0;
            this.selectFilesButton.Text = "Select Files";
            this.selectFilesButton.UseVisualStyleBackColor = true;
            // 
            // fileView
            // 
            this.fileView.FormattingEnabled = true;
            this.fileView.Location = new System.Drawing.Point(8, 72);
            this.fileView.Name = "fileView";
            this.fileView.Size = new System.Drawing.Size(768, 304);
            this.fileView.TabIndex = 3;
            // 
            // progressBar
            // 
            this.progressBar.Location = new System.Drawing.Point(8, 384);
            this.progressBar.Name = "progressBar";
            this.progressBar.Size = new System.Drawing.Size(768, 23);
            this.progressBar.TabIndex = 4;
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.addCustomFieldButton);
            this.tabPage2.Controls.Add(this.addCustomScriptButton);
            this.tabPage2.Controls.Add(this.selectTiming);
            this.tabPage2.Controls.Add(this.scriptSelector);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(624, 38);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Advanced";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // addCustomFieldButton
            // 
            this.addCustomFieldButton.Enabled = false;
            this.addCustomFieldButton.Location = new System.Drawing.Point(8, 8);
            this.addCustomFieldButton.Name = "addCustomFieldButton";
            this.addCustomFieldButton.Size = new System.Drawing.Size(116, 23);
            this.addCustomFieldButton.TabIndex = 8;
            this.addCustomFieldButton.Text = "Add Field";
            this.addCustomFieldButton.UseVisualStyleBackColor = true;
            // 
            // addCustomScriptButton
            // 
            this.addCustomScriptButton.Enabled = false;
            this.addCustomScriptButton.Location = new System.Drawing.Point(376, 8);
            this.addCustomScriptButton.Name = "addCustomScriptButton";
            this.addCustomScriptButton.Size = new System.Drawing.Size(128, 23);
            this.addCustomScriptButton.TabIndex = 1;
            this.addCustomScriptButton.Text = "Add Script";
            this.addCustomScriptButton.UseVisualStyleBackColor = true;
            // 
            // selectTiming
            // 
            this.selectTiming.Enabled = false;
            this.selectTiming.FormattingEnabled = true;
            this.selectTiming.Location = new System.Drawing.Point(256, 8);
            this.selectTiming.Name = "selectTiming";
            this.selectTiming.Size = new System.Drawing.Size(112, 21);
            this.selectTiming.TabIndex = 7;
            this.selectTiming.Text = "Script should run...";
            // 
            // scriptSelector
            // 
            this.scriptSelector.Enabled = false;
            this.scriptSelector.FormattingEnabled = true;
            this.scriptSelector.Location = new System.Drawing.Point(136, 8);
            this.scriptSelector.Name = "scriptSelector";
            this.scriptSelector.Size = new System.Drawing.Size(112, 21);
            this.scriptSelector.TabIndex = 6;
            this.scriptSelector.Text = "Select a script...";
            // 
            // convertOnlyButton
            // 
            this.convertOnlyButton.Location = new System.Drawing.Point(392, 8);
            this.convertOnlyButton.Name = "convertOnlyButton";
            this.convertOnlyButton.Size = new System.Drawing.Size(80, 23);
            this.convertOnlyButton.TabIndex = 10;
            this.convertOnlyButton.Text = "Convert Only";
            this.convertOnlyButton.UseVisualStyleBackColor = true;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.convertOnlyButton);
            this.tabPage1.Controls.Add(this.convertAndTimeStampDefaultDayButton);
            this.tabPage1.Controls.Add(this.convertAndTimeStampDefaultMonthButton);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(624, 38);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "General";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // convertAndTimeStampDefaultDayButton
            // 
            this.convertAndTimeStampDefaultDayButton.Location = new System.Drawing.Point(8, 8);
            this.convertAndTimeStampDefaultDayButton.Name = "convertAndTimeStampDefaultDayButton";
            this.convertAndTimeStampDefaultDayButton.Size = new System.Drawing.Size(184, 23);
            this.convertAndTimeStampDefaultDayButton.TabIndex = 8;
            this.convertAndTimeStampDefaultDayButton.Text = "Convert and Time Stamp - 24 Hours";
            this.convertAndTimeStampDefaultDayButton.UseVisualStyleBackColor = true;
            // 
            // convertAndTimeStampDefaultMonthButton
            // 
            this.convertAndTimeStampDefaultMonthButton.Location = new System.Drawing.Point(200, 8);
            this.convertAndTimeStampDefaultMonthButton.Name = "convertAndTimeStampDefaultMonthButton";
            this.convertAndTimeStampDefaultMonthButton.Size = new System.Drawing.Size(184, 23);
            this.convertAndTimeStampDefaultMonthButton.TabIndex = 10;
            this.convertAndTimeStampDefaultMonthButton.Text = "Convert and Time Stamp - 30 Days";
            this.convertAndTimeStampDefaultMonthButton.UseVisualStyleBackColor = true;
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Location = new System.Drawing.Point(144, 0);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(632, 64);
            this.tabControl1.TabIndex = 12;
            // 
            // PdfConversionAndTimeStampToolView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 412);
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.selectFilesButton);
            this.Controls.Add(this.progressBar);
            this.Controls.Add(this.fileView);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "PdfConversionAndTimeStampToolView";
            this.Text = "PDF Conversion & Time Stamp Tool";
            this.tabPage2.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabControl1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Button selectFilesButton;
        private System.Windows.Forms.OpenFileDialog openFileDialog;
        private System.Windows.Forms.CheckedListBox fileView;
        private System.Windows.Forms.OpenFileDialog openCustomScriptDialog;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.Button convertOnlyButton;
        private System.Windows.Forms.Button addCustomScriptButton;
        private System.Windows.Forms.ComboBox selectTiming;
        private System.Windows.Forms.ComboBox scriptSelector;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.Button convertAndTimeStampDefaultDayButton;
        private System.Windows.Forms.Button convertAndTimeStampDefaultMonthButton;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.ProgressBar progressBar;
        private System.Windows.Forms.Button addCustomFieldButton;
    }
}

