// <auto-generated />

namespace PdfScriptTool
{
    using Application = System.Windows.Forms.Application;
    internal static class Program
    {
        [System.STAThread]
        private static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new PdfScriptTool());
        }
    }
}