//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfConversionAndTimeStampTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfConversionAndTimeStampTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string DefaultTimestampFieldTitle {
            get {
                return ResourceManager.GetString("DefaultTimestampFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File failed to convert to PDF.
        /// </summary>
        internal static string FileFailedToConvertToPdfErrorMessage {
            get {
                return ResourceManager.GetString("FileFailedToConvertToPdfErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files have been saved in.
        /// </summary>
        internal static string FilesSavedInMessage {
            get {
                return ResourceManager.GetString("FilesSavedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one file..
        /// </summary>
        internal static string NoFilesSelectedErrorMessage {
            get {
                return ResourceManager.GetString("NoFilesSelectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents (*.doc;*.docx;*.pdf)|*.doc;*.docx;*.pdf.
        /// </summary>
        internal static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files....
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string OutputFolderName {
            get {
                return ResourceManager.GetString("OutputFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdf.
        /// </summary>
        internal static string PdfFileExtension {
            get {
                return ResourceManager.GetString("PdfFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string ProcessingFolderName {
            get {
                return ResourceManager.GetString("ProcessingFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Conversion And Time Stamp Tool.
        /// </summary>
        internal static string RootFolderName {
            get {
                return ResourceManager.GetString("RootFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var f = this.getField(&apos;Timestamp&apos;);
        ///f.alignment = &apos;left&apos;;
        ///f.multiline = false;
        ///f.textSize = 11;
        ///f.richText = true;
        ///var style = f.defaultStyle;
        ///style.fontFamily = [&apos;Calibri&apos;, &apos;sans-serif&apos;];
        ///f.defaultStyle = style;
        ///var t = new Array();
        ///t[0] = new Object();
        ///t[0].text = &apos;Uncontrolled 24 hours after &apos;;
        ///t[1] = new Object();
        ///t[1].text = util.printd(&apos;mm/dd/yy h:MM tt&apos;, new Date());
        ///f.richValue = t;.
        /// </summary>
        internal static string TimeStampOnPrintDefaultDay {
            get {
                return ResourceManager.GetString("TimeStampOnPrintDefaultDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var f = this.getField(&apos;Timestamp&apos;);
        ///f.alignment = &apos;left&apos;;
        ///f.multiline = false;
        ///f.textSize = 11;
        ///f.richText = true;
        ///var style = f.defaultStyle;
        ///style.fontFamily = [&apos;Calibri&apos;, &apos;sans-serif&apos;];
        ///f.defaultStyle = style;
        ///var t = new Array();
        ///t[0] = new Object();
        ///t[0].text = &apos;Uncontrolled 30 days after &apos;;
        ///t[1] = new Object();
        ///t[1].text = util.printd(&apos;mm/dd/yy h:MM tt&apos;, new Date());
        ///f.richValue = t;.
        /// </summary>
        internal static string TimeStampOnPrintDefaultMonth {
            get {
                return ResourceManager.GetString("TimeStampOnPrintDefaultMonth", resourceCulture);
            }
        }
    }
}
